version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=trust
    command: postgres -c listen_addresses='*'

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c listen_addresses='*'

  ewm-service:
    build: ./ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-server-db
      - STATS-SERVER.URL=http://STATS-SERVER:9090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=trust
    command: postgres -c listen_addresses='*'

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-server-db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c listen_addresses='*'